openapi: 3.0.3

run:
 - url: http://localhost:2209/api-docs

info:
  title: Book Management API (Typescript + Zod)
  description: API for user authentication and book management using JWT
  version: 1.0.0

servers:
  - url: http://localhost:2209

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SignupRequest:
      type: object
      required:
        - name
        - email
        - role
        - password
        - confirmPassword
      properties:
        name:
          type: string
          example: Akshay
        email:
          type: string
          example: akshay@test.com
        role:
          type: string
          enum: [user, admin]
          example: user
        password:
          type: string
          example: password123
        confirmPassword:
          type: string
          example: password123

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: akshay@test.com
        password:
          type: string
          example: password123

    BookRequest:
      type: object
      required:
        - title
        - author
        - publishedYear
      properties:
        title:
          type: string
          example: Clean Code
        author:
          type: string
          example: Robert Martin
        publishedYear:
          type: integer
          example: 2002

    BookResponse:
      type: object
      properties:
        _id:
          type: string
          example: 665c3d9f4f1a9b3a8e9f1234
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: integer
        user:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

paths:
  /api/auth/signup:
    post:
      summary: Create new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Validation error
        "409":
          description: Email already exists

  /api/auth/login:
    post:
      summary: Login user and get JWT token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /api/books:
    post:
      summary: Add new book
      tags:
        - Books
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookRequest"
      responses:
        "201":
          description: Book created successfully

    get:
      summary: Get all books for logged-in user
      tags:
        - Books
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookResponse"

  /api/books/{id}:
    get:
      summary: Get a book by ID
      tags:
        - Books
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Book found
        "404":
          description: Book not found

    put:
      summary: Update book
      tags:
        - Books
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookRequest"
      responses:
        "200":
          description: Book updated
        "404":
          description: Book not found

    delete:
      summary: Delete book
      tags:
        - Books
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Book deleted
        "404":
          description: Book not found