openapi: 3.0.3

run:
 - url: http://localhost:2209/api-docs

info:
  title: Book Management API (Typescript + Zod)
  description: API for user authentication and role-based book management using JWT
  version: 1.0.0

servers:
  - url: http://localhost:2209

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SignupRequest:
      type: object
      required:
        - name
        - email
        - role
        - password
        - confirmPassword
      properties:
        name:
          type: string
          example: Akshay
        email:
          type: string
          example: akshay@test.com
        role:
          type: string
          enum: [user, admin]
          example: user
        password:
          type: string
          example: password123
        confirmPassword:
          type: string
          example: password123

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: akshay@test.com
        password:
          type: string
          example: password123

    BookRequest:
      type: object
      required:
        - title
        - author
        - publishedYear
      properties:
        title:
          type: string
          example: Clean Code
        author:
          type: string
          example: Robert Martin
        publishedYear:
          type: integer
          example: 2008

    BookResponse:
      type: object
      properties:
        _id:
          type: string
          example: 665c3d9f4f1a9b3a8e9f1234
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        user:
          type: object
          properties:
            _id:
              type: string
            name:
              type: string
            email:
              type: string
            role:
              type: string
              enum: [user, admin]

paths:
  /api/auth/signup:
    post:
      summary: Register new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Validation error
        "409":
          description: Email already exists

  /api/auth/login:
    post:
      summary: Login user and get JWT
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /api/books:
    post:
      summary: Add new book
      tags: [Books]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookRequest"
      responses:
        "201":
          description: Book created successfully
        "400":
          description: Validation error
        "401":
          description: Unauthorized

    get:
      summary: Get books (role-based)
      description: |
        USER:
        - Gets only own books

        ADMIN:
        - Gets all users books
        - Uses aggregation pipeline with user details
      tags: [Books]
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Books fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookResponse"
        "401":
          description: Unauthorized

  /api/books/{id}:
    get:
      summary: Get book by ID
      tags: [Books]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Book found
        "404":
          description: Book not found
        "401":
          description: Unauthorized

    put:
      summary: Update book (role-based)
      description: |
        USER:
        - Can update only own book

        ADMIN:
        - Can update any user's book
      tags: [Books]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookRequest"
      responses:
        "200":
          description: Book updated successfully
        "403":
          description: Forbidden
        "404":
          description: Book not found
        "401":
          description: Unauthorized

    delete:
      summary: Delete book (admin only)
      description: |
        Only ADMIN users can delete books.
        Normal users will receive 403 Forbidden.
      tags: [Books]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Book deleted successfully
        "403":
          description: Only admin can delete books
        "404":
          description: Book not found
        "401":
          description: Unauthorized